#!/bin/bash

#Script to alter FREEC output file to include sample name and ploidy chosen by calling modifyRatio script
#RCV 6.26.2019
#EXPECTED.txt is the output of modifyRatio script (don't change that name)
#change paths as necessary


for i5 in N502 N503 N504 N505 N506 N507 N508 N517 S513
do
	for i7 in N701 N702 N703 N704 N705 N706 N707 N708 N709 N710 N711 N712 N716 N718 N719 N720 N721 N722 N723 N724 N726 N727 N728 N729
	do
	
  #change paths as necessary
	./modifyRatio.sh /share/ceph/gil213group/rcv216/sec53/$i5$i7\/$i5$i7\-sorted.bam_info.txt /share/ceph/gil213group/rcv216/sec53/$i5$i7\/$i5$i7\-sorted.bam_ratio.txt
	
  #renames EXPECTED.txt to whatever you want, useful to maintain idex names
	mv EXPECTED.txt /share/ceph/gil213group/rcv216/sec53/$i5$i7\/$i5$i7\_modified_ratio.txt
	
  #removes temp files generated by modifyRatio script
	rm headline
	rm result.txt
	
	done
done
	
